spring:
  application:
    name: hei-grades

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null

server:
  error:
    include-message: never
    include-stacktrace: never

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 3600